### ISSUE TITLE
[Transcription] error in species ids

### ISSUE THREAD

**Issue by binfalse** [whole-cell-tutors/whole-cell-reduced#12]
the species' ids in the Transcription module are not compliant to our naming scheme, e.g. line `51` in `Transcription/transcription_sbml.xml`

```
<species id="TU_001" name="MG_001 - MG_002" compartment="c" initialAmount="0" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false"/>
```

is supposed to be 

```
<species id="TU_001__c" name="MG_001 - MG_002" compartment="c" initialAmount="0" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false"/>
```

not sure how that was created, there is no script or something? does anyone remember which group created that module? according to the git log it was `0u812`... :)

**Comment by 0u812** [comment]
Working on documentation for how to generate the models here: https://github.com/whole-cell-tutors/whole-cell-reduced/wiki/Transcription_RNADecay

**Comment by 0u812** [comment]
Name substitution is too aggressive, need to apply to species, ratelaws, and stoich only.

**Comment by binfalse** [comment]
i guess you replaced the species name using a regex that depends on word boundaries? or the regex assumes that species names just consists of `[a-zA-Z]`? :)

there are a few funny artefacts such as `H2O` became `H__c2O__c`. could you please revise that?

**Comment by 0u812** [comment]
My first approach was too naive, here's an improved version, the ids look right. Please let me know if there are any problems with it.
