### ISSUE TITLE
[Translation] SBO annotations 

### ISSUE THREAD

**Issue by den2042** [whole-cell-tutors/whole-cell-reduced#14]
Where to find SBO terms for translation module?

**Comment by dagwa** [comment]
Hi,

do you know what you want to annotate?

Then search for the term (and termID) here:
http://bioportal.bioontology.org/ontologies/SBO?p=classes&conceptid=root

And add the ID to your SBML code as an attribute sboTerm

E.g.,

<math xmlns="http://www.w3.org/1998/Math/MathML">
<semantics definitionURL="http://biomodels.net/SBO/#SBO:0000062">
<lambda>
<bvar><ci 
definitionURL="http://biomodels.net/SBO/#SBO:0000036">k</ci></bvar>
<bvar><ci 
definitionURL="http://biomodels.net/SBO/#SBO:0000509">R</ci></bvar>
<apply>
<times/>
<ci>k</ci>
<ci>R</ci>
<ci>R</ci>
</apply>
</lambda>
</semantics>
</math>

SBO Terms could be added to everything actually (derived from SBase).
Further hints (SBML Spec L2)

The value of the sboTerm attribute on a Reaction should be an SBO 
identifier referring to an interaction framework. That is, the value 
should be a term derived from SBO:0000231 , “occurring entity 
representation”. (References: L2V2 Section 4.13.1; L2V3 Section 4.13.1; 
L2V4 Section 4.13.1; L2V5 Section 4.13.1.)

The value of the sboTerm attribute on a KineticLaw should be an SBO 
identifier referring to a rate law. That is, the value should be a term 
derived from SBO:0000001 , “rate law”. (References: L2V2 Section 4.13.5; 
L2V3 Section 4.13.1; L2V4 Section 4.13.1; L2V5 Section 4.13.1.)

The value of the sboTerm attribute on a FunctionDefinition should be an 
SBO identifier referring
to a mathematical expression. That is, the value should be a term 
derived from SBO:0000064 ,
“mathematical expression”. (References: L2V2 Section 4.3.3; L2V3 Section 
4.3.3; L2V4 Section 4.3.3; L2V5 Section 4.3.3.)

The value of the sboTerm attribute on a Parameter should be an SBO 
identifier referring to a quantitative parameter. That is, the value 
should be a term derived from SBO:0000002 , “quantitative systems 
description parameter”. (References: L2V2 Section 4.9.5; L2V3 Section 
4.9.5; L2V4 Section 4.9.5; L2V5 Section 4.9.5.)

The value of the sboTerm attribute on an InitialAssignment should be an 
SBO identifier referring to a mathematical expression. That is, the 
value should be a term derived from SBO:0000064 , “mathematical 
expression”. (References: L2V2 Section 4.10.3; L2V3 Section 4.10.3; L2V4 
Section 4.10.3; L2V5 Section 4.10.3.)

The value of the sboTerm attribute on a AlgebraicRule , RateRule or 
AssignmentRule should be an SBO identifier referring to a mathematical 
expression. That is, the value should be a term derived from SBO:0000064 
, “mathematical expression”. (References: L2V2 Section 4.11.1; L2V3 
Section 4.11.1; L2V4 Section 4.11.1; L2V5 Section 4.11.1.)

**Comment by den2042** [comment]
Update from Vasundra Toure:

| Type in WholeCell | SBO Term | Type in SBGN PD |
| --- | --- | --- |
| metabolite | SBO:0000247 | simple chemical |
| rna | SBO:0000354 | nucleic acid feature (=n.a.f) |
| rna-aa | SBO:0000253 | complex (simple chemical + n.a.f) |
| protein-complex | SBO:0000253 | complex (macromolecule) |
| protein-monomer | SBO:0000245 | macromolecule |

**Comment by den2042** [comment]
Annotations were added using Annotation/AddSBOtoSpecies script
