### ISSUE TITLE
[All] species ids specification

### ISSUE THREAD

**Issue by matthiaskoenig** [whole-cell-tutors/whole-cell-reduced#18]
I just had a quick look at the ProteinDecay sbml.
The rules for identifiers from the integration group are:
id : for species in cytosol, i.e. c
id__compartmentid : for all compartments not being c

but in the file are 

```
 <species id="H2O__c" name="H2O__c" compartment="c" initialAmount="1" substanceUnits="item" hasOnlySubstanceUnits="true" boundaryCondition="false" constant="false"/>
      <species id="ALA__c" name="ALA__c" compartment="c" initialAmount="1" substanceUnits="item" hasOnlySubstanceUnits="true" boundaryCondition="false" constant="false"/>
```

It looks the same in all the other groups. 
So what are the specification for the ids once and for all ???? I changed my scripts already 3 times, because the specification is changing all the time.

**Comment by cjmyers** [comment]
We did agree that cytosol was implied.  I think the species in the modules should be changed to follow this convention.  

Chris

**Comment by 0u812** [comment]
Just to confirm I understand, are you saying ids for species in the cytosol should not have the __c suffix?

**Comment by cjmyers** [comment]
Correct.

Chris

**Comment by matthiaskoenig** [comment]
@Kyle exactly, no __c for species with compartment cytosol

On Fri, Oct 16, 2015 at 7:02 PM, Kyle Medley notifications@github.com
wrote:

> Just to confirm I understand, are you saying ids for species in the
> cytosol should not have the __c suffix?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/whole-cell-tutors/whole-cell-reduced/issues/18#issuecomment-148772759
> .

## 

---

Matthias König
Computational Systems Biochemistry
Institute of Biochemistry
Charité - Universitätsmedizin Berlin
http://www.charite.de/sysbio/people/koenig/
Tel: + 49 30 450528449

## Tel: + 49 176 81168480

**Comment by den2042** [comment]
We can create versions without "__c" if needed in the Translation/Decay. But it is my understanding that  all other SBML modules adopted "__c" notation. Should we maybe wait Martin's response (he is on the flight back now)? He was creating big SBML file

**Comment by matthiaskoenig** [comment]
Just fix it once and forever.
My iterations so far
-> 1 we should use one underscore
-> 2 we should use two underscores
-> 3 we should use two underscores, but drop for cytosol
-> 4 why not go back to variant 2
I had to rewrite my scripts and recreate the files every time.

On Fri, Oct 16, 2015 at 7:18 PM, Denis notifications@github.com wrote:

> We can create versions without "__c" if needed in the Translation/Decay.
> But it is my understanding that all other SBML modules adopted "__c"
> notation. Should we maybe wait Martin's response (he is on the flight back
> now)? He was creating big SBML file
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/whole-cell-tutors/whole-cell-reduced/issues/18#issuecomment-148776650
> .

## 

---

Matthias König
Computational Systems Biochemistry
Institute of Biochemistry
Charité - Universitätsmedizin Berlin
http://www.charite.de/sysbio/people/koenig/
Tel: + 49 30 450528449

## Tel: + 49 176 81168480

**Comment by den2042** [comment]
I also vote for two underscores. It is consistent, easy to understand (notation ID__compartment), much more easy to code, de facto is already adopted in large SBML file

**Comment by binfalse** [comment]
same for me, I vote for consistently using `ID__compartment` with 2 underscores

**Comment by manikitos** [comment]
And for me. +1 for `ID__compartment`

**Comment by matthiaskoenig** [comment]
And for me. +1 for `ID__compartment`

**Comment by matthiaskoenig** [comment]
Final decision (double underscore separation for all compartments): 
id__compartment
For all compartments!
