### ISSUE TITLE
[ProteinTranslocation] many parameters not used in SBML

### ISSUE THREAD

**Issue by matthiaskoenig** [whole-cell-tutors/whole-cell-reduced#23]
The following parameters are ProteinTranslocation_v2.xml, but not used in the model. They seem to be old things just still stored.

Km1
Km1_MG_028_MONOMER__c
Km1_MG_040_MONOMER__c
Km1_MG_043_MONOMER__c
Km1_MG_045_MONOMER__c
Km1_MG_055_MONOMER__c
Km1_MG_061_MONOMER__c
Km1_MG_062_MONOMER__c
Km1_MG_064_MONOMER__c
Km1_MG_067_MONOMER__c
Km1_MG_068_MONOMER__c
Km1_MG_069_MONOMER__c
Km1_MG_071_MONOMER__c
Km1_MG_075_MONOMER__c
Km1_MG_077_MONOMER__c
Km1_MG_086_MONOMER__c
Km1_MG_095_MONOMER__c
Km1_MG_096_MONOMER__c
Km1_MG_121_MONOMER__c
Km1_MG_123_MONOMER__c
Km1_MG_130_MONOMER__c
Km1_MG_131_MONOMER__c
Km1_MG_133_MONOMER__c
Km1_MG_135_MONOMER__c
Km1_MG_146_MONOMER__c
Km1_MG_147_MONOMER__c
Km1_MG_170_MONOMER__c
Km1_MG_186_MONOMER__c
Km1_MG_210_MONOMER__c
Km1_MG_212_MONOMER__c
Km1_MG_220_MONOMER__c
Km1_MG_225_MONOMER__c
Km1_MG_241_MONOMER__c
Km1_MG_242_MONOMER__c
Km1_MG_243_MONOMER__c
Km1_MG_247_MONOMER__c
Km1_MG_256_MONOMER__c
Km1_MG_275_MONOMER__c
Km1_MG_277_MONOMER__c
Km1_MG_279_MONOMER__c
Km1_MG_280_MONOMER__c
Km1_MG_281_MONOMER__c
Km1_MG_286_MONOMER__c
Km1_MG_294_MONOMER__c
Km1_MG_306_MONOMER__c
Km1_MG_307_MONOMER__c
Km1_MG_309_MONOMER__c
Km1_MG_313_MONOMER__c
Km1_MG_314_MONOMER__c
Km1_MG_319_MONOMER__c
Km1_MG_320_MONOMER__c
Km1_MG_321_MONOMER__c
Km1_MG_322_MONOMER__c
Km1_MG_327_MONOMER__c
Km1_MG_338_MONOMER__c
Km1_MG_344_MONOMER__c
Km1_MG_348_MONOMER__c
Km1_MG_354_MONOMER__c
Km1_MG_390_MONOMER__c
Km1_MG_395_MONOMER__c
Km1_MG_397_MONOMER__c
Km1_MG_404_MONOMER__c
Km1_MG_405_MONOMER__c
Km1_MG_406_MONOMER__c
Km1_MG_411_MONOMER__c
Km1_MG_414_MONOMER__c
Km1_MG_432_MONOMER__c
Km1_MG_439_MONOMER__c
Km1_MG_447_MONOMER__c
Km1_MG_452_MONOMER__c
Km1_MG_456_MONOMER__c
Km1_MG_457_MONOMER__c
Km1_MG_478_MONOMER__c
Km1_MG_515_MONOMER__c
Km1_MG_521_MONOMER__c
Km1_MG_524_MONOMER__c
Km2
Km2_ATP__c
SecA
SecY
atp
k_cat
monomer

**Comment by manikitos** [comment]
`Km1, Km2, SecA, SecY, atp, k_cat, monomer` were add by BioUML for function by default.
Others are redundant. I'll remove them after script refactoring.
(Also names from Jonathan's table will be added #20)

**Comment by manikitos** [comment]
Partially fixed in commit 638bb48
