### ISSUE TITLE
rate law for protein decay?

### ISSUE THREAD

**Issue by den2042** [whole-cell-tutors/whole-cell-reduced#24]
@pmendes Just a double check
There is the following formula in the rate law for protein decay
![ProteinDecayRateLaw](https://github.com/whole-cell-tutors/whole-cell-reduced/blob/master/Translation/images/ProteinDecayRateLaw.png)
in the [Google doc](https://docs.google.com/document/d/1grL-bWgBCB-ClEynaPf30o72XefrWyZwJN-TXorJR3c/edit#)

Just wondering whether there is a need for a min function there as well

**Comment by binfalse** [comment]
I guess a `min` is not necessary, as there are usually just 4 enzymes and 5 at most. That's not _too_ much for a rate law. But @pmendes might nevertheless comment on that?

**Comment by pmendes** [comment]
Martin is right, there is no need for a min() in this case. I'd like to reduce the use of min() as much as possible and in this case it is definitely not needed. 

Also bear in mind that our use of min() is not the best way to represent the kinetics, even if it is currently the most practical when there are many substrates (ie >6 or so)
