### ISSUE TITLE
[Translation] min function not working in Copasi and RoadRunner

### ISSUE THREAD

**Issue by den2042** [whole-cell-tutors/whole-cell-reduced#31]
Min function (that was discussed so much at wcell2) gives an errors when Translation module is loaded in Copasi or in RoadRunned .
[FunctionsFromTraslationSubsetSBML.txt](https://github.com/whole-cell-tutors/whole-cell-reduced/files/191111/FunctionsFromTraslationSubsetSBML.txt)

Are there any ideas where the error is coming from? 

That's the selected parts from antimony (to reintroduce the idea of used min)
`// Created by libAntimony v2.8.0
function min2(a, b)
  (1/2)*((a + b) - abs(a - b));
end

function min4(a, b, c, d)
  min2(min2(a, b), min2(c, d));
end

function min8(a, b, c, d, e, f, g, h)
  min2(min4(a, b, c, d), min4(e, f, g, h));
end

function min16(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p)
  min4(min4(a, b, c, d), min4(e, f, g, h), min4(i, j, k, l), min4(m, n, o, p));
end

....

  Translation_MG_453_MONOMER: 23MG471_aa__c + 20MG472_aa__c + 6MG475_aa__c + 8MG479_aa__c + 4MG483_aa__c + 12MG484_aa__c + 2MG485_aa__c + 3MG486_aa__c + MG487_aa__c + MG488_aa__c + 17MG489_aa__c + 14MG490_aa__c + 13MG493_aa__c + 2MG495_aa__c + MG497_aa__c + 5MG499_aa__c + 17MG500_aa__c + 29MG501_aa__c + 10MG502_aa__c + 9MG503_aa__c + 3MG506_aa__c + 3MG508_aa__c + 4MG509_aa__c + 5MG510_aa__c + 22MG511_aa__c + 20MG513_aa__c + 16MG514_aa__c + 4MG518_aa__c + 5MG519_aa__c + 9MG520_aa__c + 4MG523_aa__c + 587GTP__c + 586H2O__c => MG_453_MONOMER__c + 23MG471__c + 20MG472__c + 6MG475__c + 8MG479__c + 4MG483__c + 12MG484__c + 2MG485__c + 3MG486__c + MG487__c + MG488__c + 17MG489__c + 14MG490__c + 13MG493__c + 2MG495__c + MG497__c + 5MG499__c + 17MG500__c + 29MG501__c + 10MG502__c + 9MG503__c + 3MG506__c + 3MG508__c + 4MG509__c + 5MG510__c + 22MG511__c + 20MG513__c + 16MG514__c + 4MG518__c + 5MG519__c + 9MG520__c + 4MG523__c + 587GDP__c + 587PI__c + 295H__c; (Translation_MG_453_MONOMER_kcat_(min2(min2(min8(TU_322__c, MG_173_MONOMER__c, MG_142_MONOMER__c, MG_196_MONOMER__c, MG_089_DIMER__c, MG_026_MONOMER__c, MG_451_DIMER__c, MG_433_DIMER__c, MG_258_MONOMER__c), MG_435_MONOMER__c), RIBOSOME_70S__c)_min2(min2(min2(min4(min8(min16(MG471_aa__c, MG472_aa__c, MG475_aa__c, MG479_aa__c, MG483_aa__c, MG484_aa__c, MG485_aa__c, MG486_aa__c, MG487_aa__c, MG488_aa__c, MG489_aa__c, MG490_aa__c, MG493_aa__c, MG495_aa__c, MG497_aa__c, MG499_aa__c, MG500_aa__c), MG501_aa__c, MG502_aa__c, MG503_aa__c, MG506_aa__c, MG508_aa__c, MG509_aa__c, MG510_aa__c, MG511_aa__c), MG513_aa__c, MG514_aa__c, MG518_aa__c), MG519_aa__c), MG520_aa__c), MG523_aa__c))_GTP__c^Translation_MG_453_MONOMER_m)/((1 + min2(min2(min2(min4(min8(min16(MG471_aa__c, MG472_aa__c, MG475_aa__c, MG479_aa__c, MG483_aa__c, MG484_aa__c, MG485_aa__c, MG486_aa__c, MG487_aa__c, MG488_aa__c, MG489_aa__c, MG490_aa__c, MG493_aa__c, MG495_aa__c, MG497_aa__c, MG499_aa__c, MG500_aa__c), MG501_aa__c, MG502_aa__c, MG503_aa__c, MG506_aa__c, MG508_aa__c, MG509_aa__c, MG510_aa__c, MG511_aa__c), MG513_aa__c, MG514_aa__c, MG518_aa__c), MG519_aa__c), MG520_aa__c), MG523_aa__c)/Translation_MG_453_MONOMER_k_1)_(1 + GTP__c^Translation_MG_453_MONOMER_m/Translation_MG_453_MONOMER_k_2));
`
Copasi gives a lot of errors like ">ERROR 2016-03-27 22:19:21<
  CReaction (11): Reaction 'Translation (PTS system, E1)' refers to unusable Function 'Function for Translation (PTS system, E1)'."

RoadRunner returns "RuntimeError: min8, argument count does not match, expected 8, recieved: 9, at virtual llvm::Value\* rrllvm::FunctionResolver::loadSymbolValue(const string&, const llvm::ArrayRefllvm::Value*&)"

**Comment by fbergmann** [comment]
This is to be expected ... the problem is that you call the min8 function
that was written to take exactly 8 parameters with 9 parameters. This makes
it unusable and invalid. So you will have to look at the script that
generates these expressions ... all 3 invocations have 9 arguments.

**Comment by den2042** [comment]
Indeed. 9 arguments... I've missed it.
Thank you very much
Denis
