### ISSUE TITLE
translation using simplified rate law

### ISSUE THREAD

**Issue by jtyurkovich** [whole-cell-tutors/whole-cell-reduced#4]
Since min( ) is currently up in the air, translation is using a simplified rate law; needs to be addressed once solution for min( ) is decided

**Comment by binfalse** [comment]
It's basically this line, isn't it?
https://github.com/whole-cell-tutors/whole-cell-reduced/blob/1371a2c17e3cd1a1abcb28f9a34a0e9ca805edff/Translation/translation.py#L246

To get that running we just need to fix that line, uncomment the [corresponding function](https://github.com/whole-cell-tutors/whole-cell-reduced/blob/1371a2c17e3cd1a1abcb28f9a34a0e9ca805edff/Translation/translation.py#L240) and remove the [function after](https://github.com/whole-cell-tutors/whole-cell-reduced/blob/1371a2c17e3cd1a1abcb28f9a34a0e9ca805edff/Translation/translation.py#L259). Is that correct?

**Comment by den2042** [comment]
Yes this is correct. I've added comments to make it more clear in the code.
Of note, function Make_kinetic_law_string_Translation (which is commented out) acts as if min function exists in SBML as min
