### ISSUE TITLE
[ProteinDecay] reactions' names are wrong

### ISSUE THREAD

**Issue by binfalse** [whole-cell-tutors/whole-cell-reduced#7]
currently the reactions' names equal the reactions' ids. There are proper reaction names provided in Jonathan's excel sheets. We should use them.

**Comment by binfalse** [comment]
Actually, that's still a problem. I found https://github.com/whole-cell-tutors/whole-cell-reduced/blob/1371a2c17e3cd1a1abcb28f9a34a0e9ca805edff/ProteinDecay/protein-decay.py#L285

```
check(s1.setCompartment('c'), 'set species s1 compartment')
```

and expected that everything happens in `c`. turns out that some of them are actually in e.g. `m`, so we should be careful in naming the species, instead of just appending `c`. and we also need to add the missing compartments...

**Comment by manikitos** [comment]
I think that you reopened wrong issue, it should be #5

**Comment by manikitos** [comment]
I think that you reopened wrong issue, it should be #5
